/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasBesar;

import TugasBesar.connection.ConnectionDb;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author lenovo
 */
class DataMovie {

    String id_jadwal;
    String id_studio;
    String id_film;
    String tanggal;
    String jam;

    DataMovie(String id_jadwal,
            String id_studio,
            String id_film,
            String tanggal,
            String jam) {
        this.id_jadwal = id_jadwal;
        this.id_studio = id_studio;
        this.id_film = id_film;
        this.tanggal = tanggal;
        this.jam = jam;
    }
}

public class FormJadwal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Dashboard
     */
    private String id_film;
    private ConnectionDb db;
    private JButton[] btnArray = new JButton[6];
    private JButton[] dayArray = new JButton[7];
    private int countBtn = 0;
    private int days = 7;
    private String input;
    private ArrayList<String> studio = new ArrayList<>();

    public FormJadwal(String id_film, ConnectionDb db) {
        this.db = db;
        this.id_film = id_film;
        initComponents();
        setLocationRelativeTo(null);
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void dbContent() {
        try {
            db.rs = db.perintah.executeQuery("SELECT nama_film,durasi_menit,date,desc_film,id_waktu,image FROM"
                    + " jadwal,film WHERE jadwal.id_film = '" + id_film + "' AND film.id_film ='" + id_film + "'");
            if (db.rs.next()) {
                byte[] img = db.rs.getBytes("image");
                InputStream inputStream = new ByteArrayInputStream(img);
                BufferedImage images = ImageIO.read(inputStream);
                Judul.setText(db.rs.getString("nama_film"));
                durasi.setText(db.rs.getString("durasi_menit") + " menit");
                txtDesc.setText(db.rs.getString("desc_film"));
                banner_img.setText("");
                banner_img.setIcon(new ImageIcon(images));
                Icon icn = banner_img.getIcon();
                ImageIcon icon = (ImageIcon) icn;
                Image image = icon.getImage().getScaledInstance(banner_img.getWidth(), banner_img.getHeight(), Image.SCALE_SMOOTH);
                banner_img.setIcon(new ImageIcon(image));
            }
        } catch (SQLException e) {
            System.err.println(e);
        } catch (IOException e) {
            System.err.println("seez");
        }
    }

    private void menuList(String tgl, String id) {
        // Button Wktu
        String waktu = "";
        try {
            db.rs = db.perintah.executeQuery("SELECT COUNT(*) as jumlah FROM jadwal RIGHT JOIN waktu ON waktu.id_waktu = jadwal.id_waktu"
                    + " WHERE date='" + tgl + "' AND id_film='" + id + "'" + " ORDER BY jam_mulai ASC");
            if (db.rs.next()) {
                countBtn = db.rs.getInt("jumlah");
            }
            db.rs = db.perintah.executeQuery("SELECT *,DAYNAME(date) AS nama_hari FROM jadwal RIGHT JOIN waktu ON waktu.id_waktu = jadwal.id_waktu"
                    + " RIGHT JOIN harga ON harga.id_hari=jadwal.id_hari INNER JOIN studio ON studio.id_studio=jadwal.id_studio WHERE date='" + tgl + "' AND id_film='" + id + "'" + " ORDER BY jam_mulai ASC");
            for (int i = 0; i < countBtn; i++) {
                if (db.rs.next()) {
                    waktu = db.rs.getString("jam_mulai");
                    studio.add(db.rs.getString("id_studio"));
                }
                btnArray[i] = new JButton(waktu);
                btnArray[i].setCursor(new Cursor(HAND_CURSOR));
                btnArray[i].addActionListener(this);
                conTime.add(btnArray[i]);

                // Harga Label
                Locale myIndonesianLocale = new Locale("in", "ID");
                NumberFormat rupiah = NumberFormat.getCurrencyInstance(myIndonesianLocale);
                priceLbl.setText(rupiah.format(db.rs.getInt("harga")));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    private String getDateMovie() {
        String dm = "";
        try {
            db.rs = db.perintah.executeQuery("SELECT jadwal.id_film,film.durasi_menit,jam_mulai, jadwal.date, DAYNAME(jadwal.date) as nama_hari "
                    + "FROM film RIGHT JOIN jadwal ON film.id_film=jadwal.id_film "
                    + "RIGHT JOIN waktu ON waktu.id_waktu = jadwal.id_waktu"
                    + " WHERE jadwal.id_film = '" + id_film + "'");
            if (db.rs.next()) {
                dm = db.rs.getString("date");
                return dm;
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        return dm;
    }

    private DataMovie dataMovie(String id, String tgl, String jam,String studio) {
        DataMovie dam = null;
        try {
            db.rs = db.perintah.executeQuery("SELECT * FROM jadwal LEFT JOIN waktu ON "
                    + "jadwal.id_waktu=waktu.id_waktu  INNER JOIN studio ON studio.id_studio=jadwal.id_studio"
                    + " WHERE id_film='" + id + "' and date='" + tgl + "' and jam_mulai='" + jam + "' and jadwal.id_studio='" +studio+ "'");
            if (db.rs.next()) {
                dam = new DataMovie(db.rs.getString("id_jadwal"),
                        db.rs.getString("id_studio"), db.rs.getString("id_film"),
                        db.rs.getString("date"), db.rs.getString("jam_mulai"));
                return dam;
            }
        } catch (SQLException e) {
            System.err.println("siuu");
        }
        return dam;
    }

    private void initialize() {
        dbContent();
        input = getDateMovie();
        menuList(input, id_film);
        // Buttons Hari Senin - Minggu
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = LocalDate.parse(input, formatter);
        for (int i = 0; i < days; i++) {
            LocalDate newDate = date.plusDays(i);
            dayArray[i] = new JButton(newDate.getDayOfWeek().name());
            dayArray[i].setCursor(new Cursor(HAND_CURSOR));
            dayArray[i].addActionListener(this);
            conHari.add(dayArray[i]);
            hriLbl.setText(date.getDayOfWeek().name() + ", ");
            tglLbl.setText(date.format(formatter));
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        durasi = new javax.swing.JLabel();
        banner_img = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        daftar = new javax.swing.JPanel();
        conTime = new javax.swing.JPanel();
        hriLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        priceLbl = new javax.swing.JLabel();
        tglLbl = new javax.swing.JLabel();
        conHari = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JADWAL TAYANG");

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasBesar/src/cinema.png"))); // NOI18N
        jLabel1.setText("AFUNG TZY");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Judul.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        Judul.setText("Judul Film");

        durasi.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        durasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasBesar/src/clock.png"))); // NOI18N
        durasi.setText("Jam");

        banner_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasBesar/src/borad.png"))); // NOI18N
        banner_img.setText("disinin gambarr");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Daftar Jadwal Penayangan");

        daftar.setBackground(new java.awt.Color(255, 255, 255));
        daftar.setLayout(null);

        conTime.setBackground(new java.awt.Color(255, 255, 255));
        conTime.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        daftar.add(conTime);
        conTime.setBounds(20, 60, 660, 30);

        hriLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        hriLbl.setForeground(new java.awt.Color(0, 0, 0));
        hriLbl.setText("Hari Tayang");
        daftar.add(hriLbl);
        hriLbl.setBounds(20, 0, 110, 20);
        daftar.add(jSeparator1);
        jSeparator1.setBounds(20, 100, 1090, 3);

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(0, 0, 0));
        priceLbl.setText("Harga");
        daftar.add(priceLbl);
        priceLbl.setBounds(987, 80, 90, 16);

        tglLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tglLbl.setForeground(new java.awt.Color(0, 0, 0));
        tglLbl.setText("Tanggal Penayangan");
        daftar.add(tglLbl);
        tglLbl.setBounds(110, 0, 320, 20);

        conHari.setBackground(new java.awt.Color(255, 255, 255));
        conHari.setForeground(new java.awt.Color(255, 255, 255));
        conHari.setLayout(new java.awt.GridLayout(1, 0));

        txtDesc.setEditable(false);
        txtDesc.setBackground(new java.awt.Color(255, 255, 255));
        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setText("\n");
        txtDesc.setToolTipText("");
        txtDesc.setWrapStyleWord(true);
        txtDesc.setBorder(null);
        txtDesc.setFocusable(false);
        txtDesc.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conHari, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(banner_img, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(durasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(banner_img, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("<");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked
//
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        ConnectionDb db = new ConnectionDb();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormJadwal("MV001", db).setVisible(true);
//            }
//        });
//    }
    /**
     * @param args the command line arguments
     */
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel banner_img;
    private javax.swing.JPanel conHari;
    private javax.swing.JPanel conTime;
    private javax.swing.JPanel daftar;
    private javax.swing.JLabel durasi;
    private javax.swing.JLabel hriLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel tglLbl;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables
    private String getTextTgl() {
        return tglLbl.getText();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String tgl = getDateMovie();
        for (int j = 0; j < days; j++) {
            if (dayArray[j] == e.getSource()) {
                studio.clear();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate date = LocalDate.parse(tgl, formatter);
                LocalDate newDate = date.plusDays(j);
                for (int i = 0; i < countBtn; i++) {
                    conTime.remove(btnArray[i]);
                    conTime.revalidate();
                    conTime.repaint();
                }
                hriLbl.setText(newDate.getDayOfWeek().name() + ", ");
                tglLbl.setText(newDate.format(formatter));
                menuList(newDate.format(formatter), id_film);
            }
        }
        String jam = "";
        DataMovie data;
        for (int i = 0; i < countBtn; i++) {
            if (btnArray[i] == e.getSource()) {
                System.out.println(studio);
                jam = btnArray[i].getText();
                data = dataMovie(id_film, getTextTgl(), jam,studio.get(i));
                dispose();
                new FormPetaKursi(data, db).setVisible(true);
            }
        }
    }
}
