/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TugasBesar.controllers;

import TugasBesar.connection.ConnectionDb;
import TugasBesar.FormPetaKursi;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author lenovo
 */
class DataTiket {
    String jam, nama_film, tanggal, nama_studio, kursi;
    int id_pembelian, harga;
    DataTiket(String jam, String nama_film, String tanggal, String nama_studio, String kursi, int pembelian, int harga) {
        this.jam = jam;
        this.nama_film = nama_film;
        this.tanggal = tanggal;
        this.nama_studio = nama_studio;
        this.kursi = kursi;
        this.id_pembelian = pembelian;
        this.harga = harga;
    }
}

public class FormTiket extends javax.swing.JDialog {

    /**
     * Creates new form FormTiket
     */
    private String  tanggal, id_jadwal, id_studio;
    private List<String> kursi;
    private int total;
    private ConnectionDb db;
    private int no_tiket = 0;

    public FormTiket(java.awt.Frame parent, boolean modal, FormPetaKursi pk, int jumlah_tiket, List<String> kursi, ConnectionDb db) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.kursi = kursi;
        this.id_studio = pk.id_studio;
        this.id_jadwal = pk.id_jadwal;
        this.total = jumlah_tiket;
        this.tanggal = pk.tanggal;
        this.db = db;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private List<DataTiket> dbTampilTiket(int i) {
        List<DataTiket> data = new ArrayList<DataTiket>();
        try {
            for(String output: kursi) {
            db.rs = db.perintah.executeQuery("SELECT *,DAYNAME(date) as nama_hari FROM pembelian_tiket "
                    + "LEFT JOIN jadwal ON pembelian_tiket.id_jadwal=jadwal.id_jadwal RIGHT JOIN studio "
                    + "ON jadwal.id_studio=studio.id_studio RIGHT JOIN harga ON harga.id_hari=jadwal.id_hari "
                    + "RIGHT JOIN peta_kursi ON peta_kursi.id_kursi=pembelian_tiket.id_kursi RIGHT JOIN film"
                    + " ON film.id_film=jadwal.id_film RIGHT JOIN waktu ON waktu.id_waktu=jadwal.id_waktu WHERE "
                    + "pembelian_tiket.id_jadwal='" + id_jadwal + "' AND pembelian_tiket.id_kursi='" + output + "' "
                    + "AND jadwal.id_studio='" + id_studio + "' AND DATE='" + tanggal + "'");    
                    if(db.rs.next()) {
                                        data.add(new DataTiket(
                        db.rs.getString("jam_mulai"),
                        db.rs.getString("nama_film"),
                        db.rs.getString("date"),
                        db.rs.getString("nama_studio"),
                        db.rs.getString("no_kursi"),
                        db.rs.getInt("id_pembelian"),
                        db.rs.getInt("harga")
                ));
                    }
            }
            return data;
        } catch (SQLException e) {
            System.err.println(e);
        }
        return data;
    }

    private void tampilTiket(int no_tiketTampil) {
        List<DataTiket> tiket = dbTampilTiket(no_tiketTampil);
        namaKecil.setText(tiket.get(no_tiketTampil).nama_film);
        dateKecil.setText(tiket.get(no_tiketTampil).tanggal);
        timeKecil.setText(tiket.get(no_tiketTampil).jam);
        seatKecil.setText(tiket.get(no_tiketTampil).kursi);
        studiKecil.setText(tiket.get(no_tiketTampil).nama_studio);
        priceKecil.setText(Integer.toString(tiket.get(no_tiketTampil).harga));
        idKecil.setText(Integer.toString(tiket.get(no_tiketTampil).id_pembelian));
        namaBesar.setText(tiket.get(no_tiketTampil).nama_film);
        dateBesar.setText("Date :\t " + tiket.get(no_tiketTampil).tanggal);
        timeBesar.setText("Time :\t " + tiket.get(no_tiketTampil).jam);
        seatBesar.setText("Seat :\t " + tiket.get(no_tiketTampil).kursi);
        priceBesar.setText("Price :\t " + Integer.toString(tiket.get(no_tiketTampil).harga));
        idBesar.setText("Id :\t " + Integer.toString(tiket.get(no_tiketTampil).id_pembelian));
        studioBesar.setText(tiket.get(no_tiketTampil).nama_studio);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        namaBesar = new javax.swing.JLabel();
        dateBesar = new javax.swing.JLabel();
        timeBesar = new javax.swing.JLabel();
        seatBesar = new javax.swing.JLabel();
        priceBesar = new javax.swing.JLabel();
        idBesar = new javax.swing.JLabel();
        idKecil = new javax.swing.JLabel();
        priceKecil = new javax.swing.JLabel();
        seatKecil = new javax.swing.JLabel();
        timeKecil = new javax.swing.JLabel();
        dateKecil = new javax.swing.JLabel();
        namaKecil = new javax.swing.JLabel();
        studiKecil = new javax.swing.JLabel();
        kanan = new javax.swing.JButton();
        kiri = new javax.swing.JButton();
        studioBesar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tiket Bioskop");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AFUNG TZY");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("AFUNG TZY");

        namaBesar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaBesar.setForeground(new java.awt.Color(0, 0, 0));
        namaBesar.setText("NAMA FILM");

        dateBesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateBesar.setForeground(new java.awt.Color(0, 0, 0));
        dateBesar.setText("Date : ");

        timeBesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeBesar.setForeground(new java.awt.Color(0, 0, 0));
        timeBesar.setText("Time :");

        seatBesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seatBesar.setForeground(new java.awt.Color(0, 0, 0));
        seatBesar.setText("Seat  :");

        priceBesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceBesar.setForeground(new java.awt.Color(0, 0, 0));
        priceBesar.setText("Price :");

        idBesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idBesar.setForeground(new java.awt.Color(0, 0, 0));
        idBesar.setText("Id");

        idKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        idKecil.setForeground(new java.awt.Color(0, 0, 0));
        idKecil.setText("Id");

        priceKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        priceKecil.setForeground(new java.awt.Color(0, 0, 0));
        priceKecil.setText("Price :");

        seatKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        seatKecil.setForeground(new java.awt.Color(0, 0, 0));
        seatKecil.setText("Seat  :");

        timeKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        timeKecil.setForeground(new java.awt.Color(0, 0, 0));
        timeKecil.setText("Time :");

        dateKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        dateKecil.setForeground(new java.awt.Color(0, 0, 0));
        dateKecil.setText("Date : ");

        namaKecil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaKecil.setForeground(new java.awt.Color(0, 0, 0));
        namaKecil.setText("NAMA FILM");

        studiKecil.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        studiKecil.setForeground(new java.awt.Color(0, 0, 0));
        studiKecil.setText("Studio :");

        kanan.setText(">");
        kanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kananActionPerformed(evt);
            }
        });

        kiri.setText("<");
        kiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiriActionPerformed(evt);
            }
        });

        studioBesar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studioBesar.setForeground(new java.awt.Color(0, 0, 0));
        studioBesar.setText("Studio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(kiri)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateKecil)
                            .addComponent(namaKecil)
                            .addComponent(timeKecil)
                            .addComponent(seatKecil)
                            .addComponent(idKecil)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceKecil)
                            .addComponent(studiKecil))))
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idBesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(studioBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaBesar)
                            .addComponent(dateBesar)
                            .addComponent(priceBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(seatBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kanan)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(namaKecil)
                        .addGap(18, 18, 18)
                        .addComponent(dateKecil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeKecil)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(kiri))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(seatKecil)
                                .addGap(18, 18, 18)
                                .addComponent(studiKecil)))
                        .addGap(42, 42, 42)
                        .addComponent(priceKecil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idKecil)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaBesar)
                        .addGap(18, 18, 18)
                        .addComponent(dateBesar)
                        .addGap(34, 34, 34)
                        .addComponent(timeBesar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kanan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(seatBesar)))
                        .addGap(47, 47, 47)
                        .addComponent(priceBesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idBesar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(studioBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initialize() {
        if (total == 1) {
            kanan.setVisible(false);
            kiri.setVisible(false);
            tampilTiket(no_tiket);
        } else {
            kanan.setVisible(true);
            kiri.setVisible(false);
            tampilTiket(no_tiket);
//            System.out.println(dat);
        }
    }
    private void kananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kananActionPerformed
        no_tiket++;
        if(no_tiket ==  total-1) {
           kanan.setVisible(false);
           kiri.setVisible(true);
           tampilTiket(no_tiket);
        } else {
            kiri.setVisible(true);
            kanan.setVisible(true);
            tampilTiket(no_tiket);
        }
    }//GEN-LAST:event_kananActionPerformed

    private void kiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiriActionPerformed
        no_tiket--;
        if (no_tiket == 0) {
            kiri.setVisible(false);
            kanan.setVisible(true);
            tampilTiket(no_tiket);
        } else {
            kiri.setVisible(true);
            kanan.setVisible(true);
            tampilTiket(no_tiket);
        }
    }//GEN-LAST:event_kiriActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormTiket dialog = new FormTiket();
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(total);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateBesar;
    private javax.swing.JLabel dateKecil;
    private javax.swing.JLabel idBesar;
    private javax.swing.JLabel idKecil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kanan;
    private javax.swing.JButton kiri;
    private javax.swing.JLabel namaBesar;
    private javax.swing.JLabel namaKecil;
    private javax.swing.JLabel priceBesar;
    private javax.swing.JLabel priceKecil;
    private javax.swing.JLabel seatBesar;
    private javax.swing.JLabel seatKecil;
    private javax.swing.JLabel studiKecil;
    private javax.swing.JLabel studioBesar;
    private javax.swing.JLabel timeBesar;
    private javax.swing.JLabel timeKecil;
    // End of variables declaration//GEN-END:variables
}
